#!/bin/sh

set -o errexit
set -o pipefail
set -o nounset


python /app/manage.py migrate --no-input --settings=config.settings.production
python /app/manage.py collectstatic --noinput
/usr/local/bin/gunicorn config.wsgi \
	--config='../gunicorn_config.py' \
	--log-config='../gunicorn_logging.conf' \
 	--chdir=/app
